log_level: debug
name_prefix: test

# Vars used by more than one object:
max_seq_len: &max_seq_len 5

vocab_size: &vocab_size 100
embed_size: &embed_size 16

graph:
  embedding:
    input_dim: *vocab_size
    output_dim: *embed_size
    mask_zero: True
  num_lstm_layers: 3
  lstm:
    return_sequences: True
    stateful: True
    units: 16
  dense:
    units: *vocab_size
    activation: ~

data:
  max_samples: 1000
  lower: True

trainer:
  train_params:
    batch_size: 4
    max_steps: 8
    epochs: 100
    learning_rate: 0.001
    steps_per_print: 2
    steps_per_valid: ~
  eval_params:
    steps: 10
